name: Document Loader Service

on:
  push:
    paths:
      - "document-loader-service/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop running container (if any)
        run: |
          CONTAINERS=$(sudo docker ps -q --filter "publish=8000")
          if [ -n "$CONTAINERS" ]; then
              sudo docker stop $CONTAINERS
          else
              echo "No containers found with ancestor document-loader-service."
          fi

      - name: Build and run Document Loader Service
        run: |
          cd document-loader-service/service
          sudo docker build -t document-loader-service .
          sudo docker run -d -p 8000:8000 document-loader-service
